In [8]:
#Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.

#import numpy as np

a = np.array([[10, 40], [30, 20]])
print ("Original Array is:")
print (a)

print ("Sorting the array along the first axis, we have:")
print (np.sort(a, axis = 0))

print ("Sort the array along the last axis, we have:")
print(np.sort(a, axis =1))
#OR print(np.sort(a))

print("Sort the flattened array:")
print (np.sort(a, axis = None))


Original Array is:
[[10 40]
 [30 20]]
Sorting the array along the first axis, we have:
[[10 20]
 [30 40]]
Sort the array along the last axis, we have:
[[10 40]
 [20 30]]
Sort the flattened array:
[10 20 30 40]


In [23]:
#Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.

import numpy as np

data_type = [("name", str), ("class", int), ("height", float)]
student_details = [('Rodgers', 8, 4.5), ("Hillary", 6, 5.5), ("Mary", 5, 3.5)]
print ("The list of students is:")
print (student_details)

#create a structured array
students = np.array(student_details, dtype=data_type)
print ("\nOriginal Array is:")
print (students)

print ("Sort by height gives:")
print (np.sort(students, order = 'height'))


The list of students is:
[('Rodgers', 8, 4.5), ('Hillary', 6, 5.5), ('Mary', 5, 3.5)]

Original Array is:
[('', 8, 4.5) ('', 6, 5.5) ('', 5, 3.5)]
Sort by height gives:
[('', 5, 3.5) ('', 8, 4.5) ('', 6, 5.5)]


In [29]:
#Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort by class, then height if class are equal.

import numpy as np

columns = [("name", str), ("height", float), ("class", int)]
student_details = [("John", 5.7, 4), ("Kelvin", 6.1, 8), ("Mikey", 4.9, 6)]

#create a structured array
students = np.array(student_details, dtype=data_type)
print ("The original array is:")
print (students)

#sort by class, then height if class are equal.
print (np.sort(students, order = ["class", "height"]))
#student_details = np.sort(student_details," if height <= )


The original array is:
[('', 5, 4.) ('', 6, 8.) ('', 4, 6.)]
[('', 4, 6.) ('', 5, 4.) ('', 6, 8.)]


In [34]:
#Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data.

import numpy as np

student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])

#sort by student id then by student height
indices = np.lexsort((student_id, student_height))
print("Sorted Indices")
print (indices)

print("\nSorted data")
for n in indices:
    print(student_id[n], student_height[n])


Sorted Indices
[4 0 5 3 6 1 2]

Sorted data
1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0


In [37]:
#Write a NumPy program to get the indices of the sorted elements of a given array.

import numpy as np

original_array = np.array([1023,5202,6230,1671,1682,5241,4532])
print ("Original Array is:")
print (original_array)

indices = np.argsort(original_array)
print ("\nSorted indices of the array are:")
print (indices)


Original Array is:
[1023 5202 6230 1671 1682 5241 4532]

Sorted indices of the array are:
[0 3 4 6 1 5 2]


In [39]:
#Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice).

import numpy as np

numbers = np.array([70, 50, 20, 30, -11, 60, 50, 40])
print ("Original Array is:")
print (numbers)

print ("\nAfter partitioning:")
print (np.partition(numbers, 4))



Original Array is:
[ 70  50  20  30 -11  60  50  40]

After partitioning:
[-11  30  20  40  50  50  60  70]


In [51]:
#Write a NumPy program to sort the specified number of elements from beginning of a given array.

import numpy as np

numbers = np.array([70, 50, 20, 30, -11, 60, 5, 40])
print ("Original Array is:")
print (numbers)

#sorted_array = np.array[::-1].sort()
print ("\nAfter sorting, we have:")
print (-np.sort(-numbers))


Original Array is:
[ 70  50  20  30 -11  60   5  40]

After sorting, we have:
[ 70  60  50  40  30  20   5 -11]
